version: 0.0
os: linux
files:
  - source: .
    destination: /home/ubuntu/itmVentas/
hooks:
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
  DownloadBundle:
    - location: scripts/bundle
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/backup
      timeout: 300
      runas: root  
  Install:
    - location: scripts/install
      timeout: 300
      runas: root
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after_install
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/validate_service
      timeout: 300
      runas: root